[ubuntu]
    apt = [
      "build-essential",
      "zlib1g-dev",
      "libffi-dev",
      "libssl-dev",
      "libbz2-dev",
      "libreadline-dev",
      "libsqlite3-dev",
      "liblzma-dev",
      "libncurses-dev",
      "tk-dev",
      "python3-pip",
      "python3-venv",
      "python3-full",
      "pipx",
      "nodejs",
      "npm",
      "curl",
      "fd-find",
      "fzf",
      "git",
      "jq",
      "libfuse2",
      "openssh-server",
      "ripgrep",
      "shellcheck",
      "htop",
      "sshpass",
      "tree",
      "xinput",
      "file",
      "zsh",
      "zip",
      "wireguard",
      "cmake",
      "ca-certificates",
    ]
    snap = [
      { instance = "nvim", args = "--classic" },
      { instance = "go", args = "--classic" },
      { instance = "aws-cli", args = "--channel=v1/stable --classic" },
    ]

[homebrew]
    formulae = [
      "tmux",
      "neovim",
      "jq",
      "python-yq",
      "llvm",
      "ripgrep",
      "fzf",
      "zsh",
      "pipx",
      "python@3.12",
      "rbw",
    ]
